apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}-headless
  labels: {{- include "zookeeper.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 2181
    name: client
    protocol: TCP
  - port: 2888
    name: server
    protocol: TCP
  - port: 3888
    name: leader-election
    protocol: TCP
  selector: {{- include "zookeeper.selectorLabels" . | nindent 4 }}
