apiVersion: v1
kind: Service
metadata:
  name: {{ include "solr.fullname" . }}-headless
  labels: {{- include "solr.labels" . | nindent 4 }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 8983
    name: http
    protocol: TCP
  selector: {{- include "solr.selectorLabels" . | nindent 4 }}
